# Generated by Django 4.2.6 on 2023-10-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comunicado_options_alter_entidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'verbose_name_plural': 'Comunicados'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(max_length=500, upload_to='app/images/'),
        ),
    ]
