# Generated by Django 4.2.6 on 2023-10-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comunicado_options_alter_entidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(upload_to='app/images/'),
        ),
    ]
