# Generated by Django 4.2.6 on 2023-10-22 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_entidad_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='detalle',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='detalle_corto',
        ),
    ]
