# Generated by Django 4.2.6 on 2023-10-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_detalle_comunicado_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='modificado_por',
        ),
    ]
