# Generated by Django 4.2.6 on 2023-10-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_comunicado_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Titulo'),
        ),
    ]
