# Generated by Django 4.2.6 on 2023-10-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comunicado_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
