# Generated by Django 4.2.6 on 2023-10-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_comunicado_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['id'], 'verbose_name': 'Comunicado', 'verbose_name_plural': 'Comunicados'},
        ),
    ]
